### ISSUE TITLE
Allow "none" value for charset

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig-core-c#45] opened 2018-11-11 20:50 UTC
As a developer working with text files, I want most of my source code files (`[*]`) to use Unicode encoding, specifically UTF-8 charset. However, I want to be able to disable charset rules for certain folders, such as my `examples/` directory, where I deliberately keep some non-UTF-8 and non-Unicode text files in order to test my applications. So it would be helpful if EditorConfig officially allowed more rules to be configured for most files, while allowing specific patterns (e.g., `[*.html]`) to disable the rule, such as with `charset = none`.

I see, eclint used the value `unset` by mistake. As there is no single, well-defined standard for CLI application to lint EditorConfig projects, some of the particular EditorConfig linters out there have varying degrees of support for the EditorConfig specification.

**Comment by xuhdev** [comment] 2018-11-11 23:15
Is this a duplicate of editorconfig/editorconfig#379 ?

**Closed** 2018-11-16 00:07 UTC
